[package]
name = "rocket_app_rotas"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
handlebars = "6.2.0"
rocket_dyn_templates = { version = "0.2.0", features = ["handlebars", "tera"] }
